"""Color palettes for the dark and light themes."""

THEMES = {
    "dark": {
        # Deep neutral charcoal w/ subtle warmth, cards float on top
        "bg":             "#0d0e13",
        "bg_secondary":   "#13151c",
        "bg_card":        "#181a23",
        "bg_card_hover":  "#1f222d",
        "bg_input":       "#0a0b10",
        "fg":             "#e6e8ee",
        "fg_dim":         "#7d8493",
        "fg_heading":     "#ffffff",
        "accent":         "#e94560",
        "accent_hover":   "#ff6b81",
        "accent2":        "#222633",
        "border":         "#252836",
        "border_light":   "#323647",
        "glass":          "#181a23",
        "glass_border":   "#262a38",
        "progress_bg":    "#1a1c25",
        "progress_fill":  "#e94560",
        "scrollbar":      "#2c303d",
        "scrollbar_hover":"#3a3f4f",
        "check_on":       "#e94560",
        "check_off":      "#2c303d",
        "log_bg":         "#0a0b10",
        "log_fg":         "#7d8493",
        "success":        "#3fb950",
        "warning":        "#d29922",
        "error":          "#f85149",
        "tab_active":     "#181a23",
        "tab_inactive":   "#0d0e13",
        "sync_btn":       "#e94560",
        "sync_btn_hover": "#ff6b81",
        "sync_btn_fg":    "#ffffff",
        "cancel_btn":     "#252836",
        "cancel_hover":   "#323647",
    },
    "light": {
        # Cool off-white canvas with pure white cards and soft borders
        "bg":             "#f5f6f8",
        "bg_secondary":   "#eceef2",
        "bg_card":        "#ffffff",
        "bg_card_hover":  "#fafbfc",
        "bg_input":       "#ffffff",
        "fg":             "#0f172a",
        "fg_dim":         "#64748b",
        "fg_heading":     "#0f172a",
        "accent":         "#e94560",
        "accent_hover":   "#d6304a",
        "accent2":        "#f1f3f7",
        "border":         "#e4e7ec",
        "border_light":   "#eff1f5",
        "glass":          "#ffffff",
        "glass_border":   "#e4e7ec",
        "progress_bg":    "#eef0f4",
        "progress_fill":  "#e94560",
        "scrollbar":      "#d4d8e0",
        "scrollbar_hover":"#b2b8c4",
        "check_on":       "#e94560",
        "check_off":      "#dfe3ea",
        "log_bg":         "#fafbfc",
        "log_fg":         "#475569",
        "success":        "#16a34a",
        "warning":        "#ca8a04",
        "error":          "#dc2626",
        "tab_active":     "#ffffff",
        "tab_inactive":   "#eceef2",
        "sync_btn":       "#e94560",
        "sync_btn_hover": "#d6304a",
        "sync_btn_fg":    "#ffffff",
        "cancel_btn":     "#eceef2",
        "cancel_hover":   "#dfe3ea",
    },
}
